# https://qiita.com/shaching/items/5fe3d5df691b4ec53084
version: '3'
services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/henrique/.mysql5:/var/lib/mysql
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - /home/henrique/.mysql8:/var/lib/mysql
