version: '3'
services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:7
    container_name: apm-server
    user: apm-server
    restart: unless-stopped
    ports:
      - 8200:8200
    network_mode: "bridge"
    volumes:
      - /home/henrique/.apm/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro


