version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    user: postgres
    restart: unless-stopped
    volumes:
      - /home/henrique/.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    network_mode: "bridge"
    environment:
      - POSTGRES_PASSWORD=root
